"""Framework-independent RevenueGuard domain package."""

from revenueguard_domain.cases import (
    ALLOWED_TRANSITIONS,
    TERMINAL_STATES,
    CaseState,
    CaseTransition,
    CaseTransitionError,
    RecoveryCase,
    StaleCaseVersionError,
    SubjectType,
    WorkflowType,
    can_transition,
    transition_case,
)
from revenueguard_domain.diagnosis import (
    CaseIdentity,
    Diagnosis,
    diagnose_event,
    select_case_identity,
)
from revenueguard_domain.events import (
    SCHEMA_VERSION,
    EventSource,
    NormalizedFailureCategory,
    RevenueRiskEvent,
)
from revenueguard_domain.policy import (
    ACTION_CLASSES,
    ActionClass,
    ActionType,
    CandidateAction,
    ConsentState,
    ContactChannel,
    DecisionReceipt,
    IncidentConstraint,
    IncidentScope,
    MerchantPolicySnapshot,
    PolicyDecision,
    PolicyEvaluationInput,
    PolicyResult,
    VersionBundle,
    conservative_default_policy,
    evaluate_policy,
)
from revenueguard_domain.reviews import (
    ActionFingerprintInput,
    HumanReviewDecision,
    HumanReviewRequest,
    ReviewDecisionType,
    ReviewStatus,
    decide_review,
    expire_review,
)
from revenueguard_domain.version import __version__

__all__ = [
    "ACTION_CLASSES",
    "ALLOWED_TRANSITIONS",
    "SCHEMA_VERSION",
    "TERMINAL_STATES",
    "ActionClass",
    "ActionFingerprintInput",
    "ActionType",
    "CandidateAction",
    "CaseIdentity",
    "CaseState",
    "CaseTransition",
    "CaseTransitionError",
    "ConsentState",
    "ContactChannel",
    "DecisionReceipt",
    "Diagnosis",
    "EventSource",
    "HumanReviewDecision",
    "HumanReviewRequest",
    "IncidentConstraint",
    "IncidentScope",
    "MerchantPolicySnapshot",
    "NormalizedFailureCategory",
    "PolicyDecision",
    "PolicyEvaluationInput",
    "PolicyResult",
    "RecoveryCase",
    "RevenueRiskEvent",
    "ReviewDecisionType",
    "ReviewStatus",
    "StaleCaseVersionError",
    "SubjectType",
    "VersionBundle",
    "WorkflowType",
    "__version__",
    "can_transition",
    "conservative_default_policy",
    "decide_review",
    "diagnose_event",
    "evaluate_policy",
    "expire_review",
    "select_case_identity",
    "transition_case",
]
