"""PostgreSQL persistence boundary for durable event ingestion."""

from revenueguard_integrations.persistence.action_repositories import (
    ActionPersistenceError,
    ActionRepository,
    ClaimedAction,
    RecoveryTotals,
)
from revenueguard_integrations.persistence.database import (
    AsyncSessionFactory,
    create_database_engine,
    create_session_factory,
    session_scope,
)
from revenueguard_integrations.persistence.models import (
    ActionAttempt,
    Base,
    CaseTransition,
    CommunicationConsent,
    Customer,
    DecisionReceipt,
    EventCorrelation,
    EventDispatch,
    HumanReview,
    Merchant,
    MerchantPolicyVersion,
    NormalizedEvent,
    Payment,
    PortfolioIncident,
    RecoveryAction,
    RecoveryCase,
    RecoveryCaseEvent,
    Subscription,
    VerifiedOutcome,
    WebhookEvent,
)
from revenueguard_integrations.persistence.recovery_repositories import (
    AuthoritativeFacts,
    EvidenceDisposition,
    EvidenceLinkResult,
    EvidenceOrder,
    MissingPolicyError,
    RecoveryPersistenceError,
    RecoveryRepository,
    StaleRecoveryCaseError,
    order_evidence,
)
from revenueguard_integrations.persistence.repositories import (
    DispatchFailureResult,
    EventIngestionRepository,
    WebhookInsertResult,
)

__all__ = [
    "ActionAttempt",
    "ActionPersistenceError",
    "ActionRepository",
    "AsyncSessionFactory",
    "AuthoritativeFacts",
    "Base",
    "CaseTransition",
    "ClaimedAction",
    "CommunicationConsent",
    "Customer",
    "DecisionReceipt",
    "DispatchFailureResult",
    "EventCorrelation",
    "EventDispatch",
    "EventIngestionRepository",
    "EvidenceDisposition",
    "EvidenceLinkResult",
    "EvidenceOrder",
    "HumanReview",
    "Merchant",
    "MerchantPolicyVersion",
    "MissingPolicyError",
    "NormalizedEvent",
    "Payment",
    "PortfolioIncident",
    "RecoveryAction",
    "RecoveryCase",
    "RecoveryCaseEvent",
    "RecoveryPersistenceError",
    "RecoveryRepository",
    "RecoveryTotals",
    "StaleRecoveryCaseError",
    "Subscription",
    "VerifiedOutcome",
    "WebhookEvent",
    "WebhookInsertResult",
    "create_database_engine",
    "create_session_factory",
    "order_evidence",
    "session_scope",
]
